export const MODAL_BODY_TYPES = {
    LEAD_ADD_NEW: 'LEAD_ADD_NEW',
    CONFIRMATION: 'CONFIRMATION',
    IMPORT_EXCEL: 'IMPORT_EXCEL',
};

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
    LEAD_DELETE: 'LEAD_DELETE',
  };